version: '3.3'
services:
  db:
    container_name: pg_container_bank_application
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_application
    ports:
      - "5432:5432"